# Generated by Django 4.0.4 on 2022-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
