# Generated by Django 4.0.4 on 2022-05-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_subscriber_topic_delete_content_delete_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='topic',
            new_name='topics',
        ),
    ]
